# Generated by Django 4.2.5 on 2023-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
